connector.name=clickhouse
connection-url=jdbc:clickhouse://clickhouse:8123/
connection-user=bigdata
connection-password=bigdata
clickhouse.map-string-as-varchar=true
insert.non-transactional-insert.enabled=true
